name       : librecad 
version    : 2.0.9
release    : 1
source     :
    - https://github.com/LibreCAD/LibreCAD/archive/2.0.9.tar.gz : a0a14676e167430f23a2f00220c87d2b34d711e73a8ff2368024a998f425d677
license    : GPL-2.0
summary    : LibreCAD is a free Open Source CAD application for Windows, Apple and Linux. 
description: |
    LibreCAD is a free Open Source CAD application for Windows, Apple and Linux. 
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt5Core)
    - libboost-devel
setup      : |
    qmake librecad.pro
build      : |
    %make
install    : |
    install -D -m 755 unix/librecad %installroot%/usr/bin/librecad
    install -D -m 755 unix/ttf2lff %installroot%/usr/bin/ttf2lff
    install -D -m 644 desktop/librecad.desktop %installroot%/usr/share/applications/librecad.desktop
    install -D -m 644 desktop/librecad.1 %installroot%/usr/share/man/man1/librecad.1 
    install -D -m 644 librecad/support/doc/README %installroot%/usr/share/doc/librecad/index.README
    install -D -m 644 librecad/support/doc/index.html %installroot%/usr/share/doc/librecad/index.html
    install -D -m 644 librecad/support/doc/style.css %installroot%/usr/share/doc/librecad/style.css
    install -D -m 644 librecad/support/doc/img/librecadlogo.png %installroot%/usr/share/doc/librecad/img/librecadlogo.png
    for SIZE in 16 24 32 48 64 96 128; do
        convert -scale ${SIZE} \
            desktop/graphics_icons_and_splash/Icon\ LibreCAD/Icon_Librecad.svg $srcdir/librecad.png
        install -D -m0644 $srcdir/librecad.png $installdir/usr/share/icons/hicolor/${SIZE}x${SIZE}/apps/librecad.png
    done
    install -D -m 644 desktop/graphics_icons_and_splash/Icon\ LibreCAD/Icon_Librecad.svg %installroot%/usr/share/icons/hicolor/scalable/apps/librecad.svg
    mkdir -p %installroot%/usr/share/librecad/
    cp -r unix/resources/{library,patterns,fonts,qm} %installroot%/usr/share/librecad/
