name       : librecad
version    : 2.2.0
release    : 9
source     :
    - https://github.com/LibreCAD/LibreCAD/archive/refs/tags/2.2.0.tar.gz : dfce6f290b89707a0717789aa0cdea4ca5a96685fa0e65cfc49d70166bd182f2
homepage   : https://librecad.org/
license    : GPL-2.0-or-*later
summary    : LibreCAD is a free Open Source CAD application for Windows, Apple and Linux
component  : office
description: |
    LibreCAD is a 2D CAD drawing tool based on the community edition of QCAD. LibreCAD uses the cross-platform framework Qt, which means it works with most operating systems.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(muparser)
    - libboost-devel
setup      : |
    %qmake librecad.pro
build      : |
    %make
install    : |
    install -Dm00755 unix/librecad %installroot%/usr/bin/librecad
    install -Dm00755 unix/ttf2lff %installroot%/usr/bin/ttf2lff
    install -Dm00644 desktop/librecad.desktop %installroot%/usr/share/applications/librecad.desktop
    install -Dm00644 desktop/librecad.1 %installroot%/usr/share/man/man1/librecad.1 
    install -Dm00644 librecad/support/doc/README %installroot%/usr/share/doc/librecad/index.README
    install -Dm00644 librecad/support/doc/index.html %installroot%/usr/share/doc/librecad/index.html
    install -Dm00644 librecad/support/doc/style.css %installroot%/usr/share/doc/librecad/style.css
    install -Dm00644 librecad/support/doc/img/librecadlogo.png %installroot%/usr/share/doc/librecad/img/librecadlogo.png
    for SIZE in 16 24 32 48 64 96 128; do
        convert -scale ${SIZE} \
            desktop/graphics_icons_and_splash/Icon\ LibreCAD/Icon_Librecad.svg $workdir/librecad.png
        install -Dm00644 $workdir/librecad.png $installdir/usr/share/icons/hicolor/${SIZE}x${SIZE}/apps/librecad.png
    done
    install -Dm00644 desktop/graphics_icons_and_splash/Icon\ LibreCAD/Icon_Librecad.svg %installroot%/usr/share/icons/hicolor/scalable/apps/librecad.svg
    mkdir -p %installroot%/usr/share/librecad/
    cp -r unix/resources/{library,patterns,fonts,qm} %installroot%/usr/share/librecad/

    rm -rf $installdir/usr/share/doc

